run:
  timeout: 5m

linters-settings:
  gocyclo:
    min-complexity: 15
  goconst:
    min-len: 3
    min-occurrences: 3
  errcheck:
    exclude-functions:
      - fmt.Fprintln
      - fmt.Fprintf
      - fmt.Printf
      - fmt.Println
      - (*github.com/olekukonko/tablewriter.Table).Append
      - (*github.com/olekukonko/tablewriter.Table).Render
      - (*text/tabwriter.Writer).Flush
      - (net/http.ResponseWriter).Write
      - (*github.com/spf13/cobra.Command).MarkFlagRequired
  staticcheck:
    checks: ["all", "-QF1008"]

linters:
  disable-all: true
  enable:
    - errcheck
    - govet
    - staticcheck
    - unused
    - ineffassign
    - gocyclo
    - goconst
    - misspell
    - revive

issues:
  exclude-rules:
    - path: cmd/thecloud
      linters:
        - errcheck
    - path: pkg/sdk
      linters:
        - errcheck
    - path: internal/handlers/ws
      linters:
        - errcheck
    # Test files: allow repeated strings (test fixtures) and higher complexity
    - path: _test\.go
      linters:
        - goconst
        - gocyclo
