ALTER TABLE clusters 
    ADD COLUMN IF NOT EXISTS ha_enabled BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS api_server_lb_address TEXT,
    ADD COLUMN IF NOT EXISTS job_id TEXT;

ALTER TABLE load_balancers
    ADD COLUMN IF NOT EXISTS ip TEXT;
