ALTER TABLE instances 
DROP COLUMN IF EXISTS volume_binds,
DROP COLUMN IF EXISTS env,
DROP COLUMN IF EXISTS cmd,
DROP COLUMN IF EXISTS cpu_limit,
DROP COLUMN IF EXISTS memory_limit,
DROP COLUMN IF EXISTS disk_limit;
